class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :new, :create]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy
  before_filter :logged_in_user, :only => [:new, :create]

  def show # page that shows info about the user
    @user = User.find(params[:id])
    @entries = @user.entries.paginate(:page => params[:page])
    @title = @user.name  # in rails3, all embedded ruby text is escaped
                         # so "<" becomes "&lt;"
  end

  def new # page that allows for creation of a new user!!!
    @user = User.new
    @title = "Sign up"
  end

  def create #method for saving new user to db
    @user = User.new(params[:user])
    if @user.save
      #handle a successful save.
      sign_in @user
      flash[:success] = "Welcome to the POVRay shortcode contest!"
      redirect_to @user
    else
      @title = "Sign up"
      @user.password = ""
      @user.password_confirmation = ""
      render 'new'
    end
  end

  def edit
 #   @user = User.find(params[:id]) -- removed when i added the correct_user function
    @title = "Edit user" 
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def index
    @title = "All Users"
    @users = User.paginate(:page => params[:page]) # :page generated by will_paginate
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def voting_for
    #list all the entries that this user has voted for
    @user = User.find(params[:id])
    @title = @user.name + "'s votes"
    @entries = @user.voting_for.entries
  end

  private
  
    def correct_user
      @user = User.find(params[:id])  #this gets :id from the current url, right?
      redirect_to(root_path) unless current_user?(@user) #current_user? is in app/helpers/sessions_helper
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    #exercise 10.6.3 
    def logged_in_user
      redirect_to(root_path) unless !signed_in?
    end 
end
